window.vocabulary = window.vocabulary = [
  {"chinese": "你", "pinyin": "nǐ", "english": "you", "russian": "ты"},
  {"chinese": "我", "pinyin": "wǒ", "english": "I", "russian": "я"},
  {"chinese": "他", "pinyin": "tā", "english": "he", "russian": "он"},
  {"chinese": "她", "pinyin": "tā", "english": "she", "russian": "она"},
  {"chinese": "它", "pinyin": "tā", "english": "it", "russian": "оно"},
  {"chinese": "是", "pinyin": "shì", "english": "to be", "russian": "быть"},
  {"chinese": "有", "pinyin": "yǒu", "english": "to have", "russian": "иметь"},
  {"chinese": "在", "pinyin": "zài", "english": "at", "russian": "в"},
  {"chinese": "和", "pinyin": "hé", "english": "and", "russian": "и"},
  {"chinese": "也", "pinyin": "yě", "english": "also", "russian": "тоже"},
  {"chinese": "都", "pinyin": "dōu", "english": "all", "russian": "все"},
  {"chinese": "不", "pinyin": "bù", "english": "no", "russian": "не"},
  {"chinese": "很", "pinyin": "hěn", "english": "very", "russian": "очень"},
  {"chinese": "好", "pinyin": "hǎo", "english": "good", "russian": "хороший"},
  {"chinese": "吃", "pinyin": "chī", "english": "to eat", "russian": "есть"},
  {"chinese": "喝", "pinyin": "hē", "english": "to drink", "russian": "пить"},
  {"chinese": "看", "pinyin": "kàn", "english": "to look", "russian": "смотреть"},
  {"chinese": "听", "pinyin": "tīng", "english": "to listen", "russian": "слушать"},
  {"chinese": "说", "pinyin": "shuō", "english": "to speak", "russian": "говорить"},
  {"chinese": "读", "pinyin": "dú", "english": "to read", "russian": "читать"},
  {"chinese": "写", "pinyin": "xiě", "english": "to write", "russian": "писать"},
  {"chinese": "走", "pinyin": "zǒu", "english": "to walk", "russian": "ходить"},
  {"chinese": "来", "pinyin": "lái", "english": "to come", "russian": "приходить"},
  {"chinese": "去", "pinyin": "qù", "english": "to go", "russian": "идти"},
  {"chinese": "睡", "pinyin": "shuì", "english": "to sleep", "russian": "спать"},
  {"chinese": "坐", "pinyin": "zuò", "english": "to sit", "russian": "сидеть"},
  {"chinese": "站", "pinyin": "zhàn", "english": "to stand", "russian": "стоять"},
  {"chinese": "开", "pinyin": "kāi", "english": "to open", "russian": "открыть"},
  {"chinese": "关", "pinyin": "guān", "english": "to close", "russian": "закрыть"},
  {"chinese": "做", "pinyin": "zuò", "english": "to do", "russian": "делать"},
  {"chinese": "工作", "pinyin": "gōngzuò", "english": "to work", "russian": "работать"},
  {"chinese": "学习", "pinyin": "xuéxí", "english": "to study", "russian": "учиться"},
  {"chinese": "想", "pinyin": "xiǎng", "english": "to think", "russian": "думать"},
  {"chinese": "知道", "pinyin": "zhīdào", "english": "to know", "russian": "знать"},
  {"chinese": "要", "pinyin": "yào", "english": "to want", "russian": "хотеть"},
  {"chinese": "给", "pinyin": "gěi", "english": "to give", "russian": "давать"},
  {"chinese": "找", "pinyin": "zhǎo", "english": "to find", "russian": "найти"},
  {"chinese": "买", "pinyin": "mǎi", "english": "to buy", "russian": "покупать"},
  {"chinese": "卖", "pinyin": "mài", "english": "to sell", "russian": "продавать"},
  {"chinese": "爱", "pinyin": "ài", "english": "to love", "russian": "любить"},
  {"chinese": "喜欢", "pinyin": "xǐhuān", "english": "to like", "russian": "нравиться"},
  {"chinese": "可以", "pinyin": "kěyǐ", "english": "can", "russian": "можно"},
  {"chinese": "会", "pinyin": "huì", "english": "can", "russian": "уметь"},
  {"chinese": "能", "pinyin": "néng", "english": "can", "russian": "мочь"},
  {"chinese": "跑", "pinyin": "pǎo", "english": "to run", "russian": "бежать"},
  {"chinese": "跳", "pinyin": "tiào", "english": "to jump", "russian": "прыгать"},
  {"chinese": "笑", "pinyin": "xiào", "english": "to laugh", "russian": "смеяться"},
  {"chinese": "哭", "pinyin": "kū", "english": "to cry", "russian": "плакать"},
  {"chinese": "唱", "pinyin": "chàng", "english": "to sing", "russian": "петь"},
  {"chinese": "跳舞", "pinyin": "tiàowǔ", "english": "to dance", "russian": "танцевать"},
  {"chinese": "玩", "pinyin": "wán", "english": "to play", "russian": "играть"},
  {"chinese": "休息", "pinyin": "xiūxi", "english": "to rest", "russian": "отдыхать"},
  {"chinese": "一", "pinyin": "yī", "english": "one", "russian": "один"},
  {"chinese": "二", "pinyin": "èr", "english": "two", "russian": "два"},
  {"chinese": "三", "pinyin": "sān", "english": "three", "russian": "три"},
  {"chinese": "四", "pinyin": "sì", "english": "four", "russian": "четыре"},
  {"chinese": "五", "pinyin": "wǔ", "english": "five", "russian": "пять"},
  {"chinese": "六", "pinyin": "liù", "english": "six", "russian": "шесть"},
  {"chinese": "七", "pinyin": "qī", "english": "seven", "russian": "семь"},
  {"chinese": "八", "pinyin": "bā", "english": "eight", "russian": "восемь"},
  {"chinese": "九", "pinyin": "jiǔ", "english": "nine", "russian": "девять"},
  {"chinese": "十", "pinyin": "shí", "english": "ten", "russian": "десять"},
  {"chinese": "百", "pinyin": "bǎi", "english": "hundred", "russian": "сто"},
  {"chinese": "千", "pinyin": "qiān", "english": "thousand", "russian": "тысяча"},
  {"chinese": "万", "pinyin": "wàn", "english": "ten thousand", "russian": "десять тысяч"},
  {"chinese": "多少", "pinyin": "duōshao", "english": "how much", "russian": "сколько"},
  {"chinese": "几", "pinyin": "jǐ", "english": "how many", "russian": "сколько"},
  {"chinese": "第一", "pinyin": "dìyī", "english": "first", "russian": "первый"},
  {"chinese": "第二", "pinyin": "dìèr", "english": "second", "russian": "второй"},
  {"chinese": "第三", "pinyin": "dìsān", "english": "third", "russian": "третий"},
  {"chinese": "第四", "pinyin": "dìsì", "english": "fourth", "russian": "четвёртый"},
  {"chinese": "第五", "pinyin": "dìwǔ", "english": "fifth", "russian": "пятый"},
  {"chinese": "大", "pinyin": "dà", "english": "big", "russian": "большой"},
  {"chinese": "小", "pinyin": "xiǎo", "english": "small", "russian": "маленький"},
  {"chinese": "长", "pinyin": "cháng", "english": "long", "russian": "длинный"},
  {"chinese": "短", "pinyin": "duǎn", "english": "short", "russian": "короткий"},
  {"chinese": "高", "pinyin": "gāo", "english": "tall", "russian": "высокий"},
  {"chinese": "矮", "pinyin": "ǎi", "english": "short", "russian": "низкий"},
  {"chinese": "快", "pinyin": "kuài", "english": "fast", "russian": "быстрый"},
  {"chinese": "慢", "pinyin": "màn", "english": "slow", "russian": "медленный"},
  {"chinese": "冷", "pinyin": "lěng", "english": "cold", "russian": "холодный"},
  {"chinese": "热", "pinyin": "rè", "english": "hot", "russian": "горячий"},
  {"chinese": "新", "pinyin": "xīn", "english": "new", "russian": "новый"},
  {"chinese": "旧", "pinyin": "jiù", "english": "old", "russian": "старый"},
  {"chinese": "干净", "pinyin": "gānnjìng", "english": "clean", "russian": "чистый"},
  {"chinese": "脏", "pinyin": "zāng", "english": "dirty", "russian": "грязный"},
  {"chinese": "漂亮", "pinyin": "piàoliàng", "english": "beautiful", "russian": "красивый"},
  {"chinese": "丑", "pinyin": "chǒu", "english": "ugly", "russian": "уродливый"},
  {"chinese": "聪明", "pinyin": "cōngming", "english": "smart", "russian": "умный"},
  {"chinese": "傻", "pinyin": "shǎ", "english": "stupid", "russian": "глупый"},
  {"chinese": "强", "pinyin": "qiáng", "english": "strong", "russian": "сильный"},
  {"chinese": "弱", "pinyin": "ruò", "english": "weak", "russian": "слабый"},
  {"chinese": "忙", "pinyin": "máng", "english": "busy", "russian": "занятой"},
  {"chinese": "闲", "pinyin": "xián", "english": "free", "russian": "свободный"},
  {"chinese": "人", "pinyin": "rén", "english": "person", "russian": "человек"},
  {"chinese": "男人", "pinyin": "nánrén", "english": "man", "russian": "мужчина"},
  {"chinese": "女人", "pinyin": "nǚrén", "english": "woman", "russian": "женщина"},
  {"chinese": "男孩", "pinyin": "nánh", "english": "boy", "russian": "мальчик"},
  {"chinese": "女孩", "pinyin": "nǚhái", "english": "girl", "russian": "девочка"},
  {"chinese": "儿子", "pinyin": "érzi", "english": "son", "russian": "сын"},
  {"chinese": "女儿", "pinyin": "nǚ'ér", "english": "daughter", "russian": "дочь"},
  {"chinese": "父亲", "pinyin": "fùqin", "english": "father", "russian": "отец"},
  {"chinese": "爸爸", "pinyin": "bàba", "english": "dad", "russian": "папа"},
  {"chinese": "母亲", "pinyin": "mǔqin", "english": "mother", "russian": "мать"},
  {"chinese": "妈妈", "pinyin": "māma", "english": "mom", "russian": "мама"},
  {"chinese": "哥哥", "pinyin": "gēge", "english": "older brother", "russian": "старший брат"},
  {"chinese": "弟弟", "pinyin": "dìdi", "english": "younger brother", "russian": "младший брат"},
  {"chinese": "姐姐", "pinyin": "jiějie", "english": "older sister", "russian": "старшая сестра"},
  {"chinese": "妹妹", "pinyin": "mèimei", "english": "younger sister", "russian": "младшая сестра"},
  {"chinese": "祖父", "pinyin": "zǔfù", "english": "grandfather", "russian": "дедушка"},
  {"chinese": "祖母", "pinyin": "zǔmǔ", "english": "grandmother", "russian": "бабушка"},
  {"chinese": "家", "pinyin": "jiā", "english": "home", "russian": "дом"},
  {"chinese": "学校", "pinyin": "xuéxiào", "english": "school", "russian": "школа"},
  {"chinese": "老师", "pinyin": "lǎoshī", "english": "teacher", "russian": "учитель"},
  {"chinese": "学生", "pinyin": "xuésheng", "english": "student", "russian": "студент"},
  {"chinese": "朋友", "pinyin": "péngyou", "english": "friend", "russian": "друг"},
  {"chinese": "同学", "pinyin": "tóngxué", "english": "classmate", "russian": "одноклассник"},
  {"chinese": "同事", "pinyin": "tóngshì", "english": "colleague", "russian": "коллега"},
  {"chinese": "医生", "pinyin": "yīshēng", "english": "doctor", "russian": "врач"},
  {"chinese": "护士", "pinyin": "hùshi", "english": "nurse", "russian": "медсестра"},
  {"chinese": "警察", "pinyin": "jǐngchá", "english": "police", "russian": "полицейский"},
  {"chinese": "工人", "pinyin": "gōngrén", "english": "worker", "russian": "рабочий"},
  {"chinese": "农民", "pinyin": "nóngmín", "english": "farmer", "russian": "крестьянин"},
  {"chinese": "商人", "pinyin": "shāngrén", "english": "merchant", "russian": "торговец"},
  {"chinese": "司机", "pinyin": "sījī", "english": "driver", "russian": "водитель"},
  {"chinese": "演员", "pinyin": "yǎnyuán", "english": "actor", "russian": "актёр"},
  {"chinese": "音乐家", "pinyin": "yīnyuèjiā", "english": "musician", "russian": "музыкант"},
  {"chinese": "画家", "pinyin": "huàjiā", "english": "painter", "russian": "художник"},
  {"chinese": "作家", "pinyin": "zuòjiā", "english": "writer", "russian": "писатель"},
  {"chinese": "工程师", "pinyin": "gōngchéngshī", "english": "engineer", "russian": "инженер"},
  {"chinese": "设计师", "pinyin": "shèjìshī", "english": "designer", "russian": "дизайнер"},
  {"chinese": "书", "pinyin": "shū", "english": "book", "russian": "книга"},
  {"chinese": "笔", "pinyin": "bǐ", "english": "pen", "russian": "ручка"},
  {"chinese": "纸", "pinyin": "zhǐ", "english": "paper", "russian": "бумага"},
  {"chinese": "桌子", "pinyin": "zhuōzi", "english": "table", "russian": "стол"},
  {"chinese": "椅子", "pinyin": "yǐzi", "english": "chair", "russian": "стул"},
  {"chinese": "床", "pinyin": "chuáng", "english": "bed", "russian": "кровать"},
  {"chinese": "门", "pinyin": "mén", "english": "door", "russian": "дверь"},
  {"chinese": "窗户", "pinyin": "chuānghù", "english": "window", "russian": "окно"},
  {"chinese": "房间", "pinyin": "fángjiān", "english": "room", "russian": "комната"},
  {"chinese": "客厅", "pinyin": "kètīng", "english": "living room", "russian": "гостиная"},
  {"chinese": "卧室", "pinyin": "wòshì", "english": "bedroom", "russian": "спальня"},
  {"chinese": "厨房", "pinyin": "chúfáng", "english": "kitchen", "russian": "кухня"},
  {"chinese": "卫生间", "pinyin": "wèishēngjiān", "english": "bathroom", "russian": "ванная"},
  {"chinese": "墙", "pinyin": "qiáng", "english": "wall", "russian": "стена"},
  {"chinese": "天花板", "pinyin": "tiānhuābǎn", "english": "ceiling", "russian": "потолок"},
  {"chinese": "地板", "pinyin": "dìbǎn", "english": "floor", "russian": "пол"},
  {"chinese": "灯", "pinyin": "dēng", "english": "light", "russian": "лампа"},
  {"chinese": "手机", "pinyin": "shǒujī", "english": "mobile phone", "russian": "мобильный телефон"},
  {"chinese": "电脑", "pinyin": "diànnǎo", "english": "computer", "russian": "компьютер"},
  {"chinese": "电视", "pinyin": "diànshì", "english": "television", "russian": "телевизор"},
  {"chinese": "电话", "pinyin": "diànhuà", "english": "telephone", "russian": "телефон"},
  {"chinese": "钟", "pinyin": "zhōng", "english": "clock", "russian": "часы"},
  {"chinese": "表", "pinyin": "biǎo", "english": "watch", "russian": "наручные часы"},
  {"chinese": "水", "pinyin": "shuǐ", "english": "water", "russian": "вода"},
  {"chinese": "饭", "pinyin": "fàn", "english": "rice", "russian": "рис"},
  {"chinese": "菜", "pinyin": "cài", "english": "dish", "russian": "блюдо"},
  {"chinese": "肉", "pinyin": "ròu", "english": "meat", "russian": "мясо"},
  {"chinese": "鱼", "pinyin": "yú", "english": "fish", "russian": "рыба"},
  {"chinese": "鸡", "pinyin": "jī", "english": "chicken", "russian": "курица"},
  {"chinese": "猪", "pinyin": "zhū", "english": "pork", "russian": "свинина"},
  {"chinese": "牛", "pinyin": "niú", "english": "beef", "russian": "говядина"},
  {"chinese": "羊", "pinyin": "yáng", "english": "lamb", "russian": "баранина"},
  {"chinese": "面包", "pinyin": "miànbāo", "english": "bread", "russian": "хлеб"},
  {"chinese": "米饭", "pinyin": "mǐfàn", "english": "cooked rice", "russian": "варёный рис"},
  {"chinese": "馄饨", "pinyin": "húntun", "english": "wonton", "russian": "вонтон"},
  {"chinese": "面条", "pinyin": "miàntiáo", "english": "noodles", "russian": "лапша"},
  {"chinese": "汤", "pinyin": "tāng", "english": "soup", "russian": "суп"},
  {"chinese": "蛋", "pinyin": "dàn", "english": "egg", "russian": "яйцо"},
  {"chinese": "花生", "pinyin": "huāshēng", "english": "peanut", "russian": "арахис"},
  {"chinese": "黄瓜", "pinyin": "huángguā", "english": "cucumber", "russian": "огурец"},
  {"chinese": "番茄", "pinyin": "fānqié", "english": "tomato", "russian": "помидор"},
  {"chinese": "土豆", "pinyin": "tǔdòu", "english": "potato", "russian": "картофель"},
  {"chinese": "洋葱", "pinyin": "yángcōng", "english": "onion", "russian": "лук"},
  {"chinese": "大蒜", "pinyin": "dàsuàn", "english": "garlic", "russian": "чеснок"},
  {"chinese": "盐", "pinyin": "yán", "english": "salt", "russian": "соль"},
  {"chinese": "糖", "pinyin": "táng", "english": "sugar", "russian": "сахар"},
  {"chinese": "油", "pinyin": "yóu", "english": "oil", "russian": "масло"},
  {"chinese": "醋", "pinyin": "cù", "english": "vinegar", "russian": "уксус"},
  {"chinese": "酱", "pinyin": "jiàng", "english": "sauce", "russian": "соус"},
  {"chinese": "饼", "pinyin": "bǐng", "english": "cake", "russian": "пирог"},
  {"chinese": "糕", "pinyin": "gāo", "english": "cake", "russian": "кекс"},
  {"chinese": "馒头", "pinyin": "mántou", "english": "steamed bun", "russian": "паровая булочка"},
  {"chinese": "粥", "pinyin": "zhōu", "english": "porridge", "russian": "каша"},
  {"chinese": "肉类", "pinyin": "ròulèi", "english": "meat type", "russian": "мясной продукт"},
  {"chinese": "蔬菜", "pinyin": "shūcài", "english": "vegetable", "russian": "овощ"},
  {"chinese": "水果", "pinyin": "shuǐguǒ", "english": "fruit", "russian": "фрукт"},
  {"chinese": "苹果", "pinyin": "píngguǒ", "english": "apple", "russian": "яблоко"},
  {"chinese": "香蕉", "pinyin": "xiāngjiāo", "english": "banana", "russian": "банан"},
  {"chinese": "橙子", "pinyin": "chéngzi", "english": "orange", "russian": "апельсин"},
  {"chinese": "葡萄", "pinyin": "pútao", "english": "grape", "russian": "виноград"},
  {"chinese": "西瓜", "pinyin": "xīguā", "english": "watermelon", "russian": "арбуз"},
  {"chinese": "草莓", "pinyin": "cǎoméi", "english": "strawberry", "russian": "клубника"},
  {"chinese": "梨", "pinyin": "lí", "english": "pear", "russian": "груша"},
  {"chinese": "桃", "pinyin": "táo", "english": "peach", "russian": "персик"},
  {"chinese": "奶", "pinyin": "nǎi", "english": "milk", "russian": "молоко"},
  {"chinese": "奶酪", "pinyin": "nǎilào", "english": "cheese", "russian": "сыр"},
  {"chinese": "酸奶", "pinyin": "suānnǎi", "english": "yogurt", "russian": "йогурт"},
  {"chinese": "冰淇淋", "pinyin": "bīngqīlín", "english": "ice cream", "russian": "мороженое"},
  {"chinese": "饮料", "pinyin": "yǐnliào", "english": "beverage", "russian": "напиток"},
  {"chinese": "茶", "pinyin": "chá", "english": "tea", "russian": "чай"},
  {"chinese": "咖啡", "pinyin": "kāfēi", "english": "coffee", "russian": "кофе"},
  {"chinese": "牛奶", "pinyin": "niúnǎi", "english": "milk", "russian": "молоко"},
  {"chinese": "果汁", "pinyin": "guǒzhī", "english": "juice", "russian": "сок"},
  {"chinese": "汽水", "pinyin": "qìshuǐ", "english": "soda", "russian": "газированная вода"},
  {"chinese": "啤酒", "pinyin": "píjiǔ", "english": "beer", "russian": "пиво"},
  {"chinese": "葡萄酒", "pinyin": "pútaoyóujiǔ", "english": "wine", "russian": "вино"},
  {"chinese": "衣服", "pinyin": "yīfu", "english": "clothing", "russian": "одежда"},
  {"chinese": "衣", "pinyin": "yī", "english": "clothes", "russian": "одежда"},
  {"chinese": "裤子", "pinyin": "kùzi", "english": "pants", "russian": "брюки"},
  {"chinese": "裙子", "pinyin": "qúnzi", "english": "skirt", "russian": "юбка"},
  {"chinese": "衬衣", "pinyin": "chènyi", "english": "shirt", "russian": "рубашка"},
  {"chinese": "毛衣", "pinyin": "máoyī", "english": "sweater", "russian": "свитер"},
  {"chinese": "夹克", "pinyin": "jiakè", "english": "jacket", "russian": "куртка"},
  {"chinese": "大衣", "pinyin": "dàyī", "english": "coat", "russian": "пальто"},
  {"chinese": "鞋", "pinyin": "xié", "english": "shoe", "russian": "обувь"},
  {"chinese": "靴", "pinyin": "xuē", "english": "boot", "russian": "ботинок"},
  {"chinese": "帽子", "pinyin": "màozi", "english": "hat", "russian": "шапка"},
  {"chinese": "领带", "pinyin": "lǐngdài", "english": "tie", "russian": "галстук"},
  {"chinese": "手套", "pinyin": "shǒutào", "english": "gloves", "russian": "перчатки"},
  {"chinese": "围巾", "pinyin": "wéijīn", "english": "scarf", "russian": "шарф"},
  {"chinese": "帮", "pinyin": "bāng", "english": "to help", "russian": "помогать"},
  {"chinese": "医院", "pinyin": "yīyuàn", "english": "hospital", "russian": "больница"},
  {"chinese": "病", "pinyin": "bìng", "english": "disease", "russian": "болезнь"},
  {"chinese": "药", "pinyin": "yào", "english": "medicine", "russian": "лекарство"},
  {"chinese": "头疼", "pinyin": "tóuténg", "english": "headache", "russian": "головная боль"},
  {"chinese": "发烧", "pinyin": "fāshāo", "english": "fever", "russian": "лихорадка"},
  {"chinese": "感冒", "pinyin": "gǎnmào", "english": "cold", "russian": "простуда"},
  {"chinese": "健康", "pinyin": "jiànkāng", "english": "health", "russian": "здоровье"},
  {"chinese": "运动", "pinyin": "yùndòng", "english": "sports", "russian": "спорт"},
  {"chinese": "足球", "pinyin": "zúqiú", "english": "football", "russian": "футбол"},
  {"chinese": "篮球", "pinyin": "lánqiú", "english": "basketball", "russian": "баскетбол"},
  {"chinese": "排球", "pinyin": "páiqiú", "english": "volleyball", "russian": "волейбол"},
  {"chinese": "乒乓球", "pinyin": "pīngpāngqiú", "english": "table tennis", "russian": "настольный теннис"},
  {"chinese": "网球", "pinyin": "wǎngqiú", "english": "tennis", "russian": "теннис"},
  {"chinese": "羽毛球", "pinyin": "yǔmáoqiú", "english": "badminton", "russian": "бадминтон"},
  {"chinese": "游泳", "pinyin": "yóuyǒng", "english": "swimming", "russian": "плавание"},
  {"chinese": "骑马", "pinyin": "qīmǎ", "english": "horseback riding", "russian": "верховая езда"},
  {"chinese": "登山", "pinyin": "dēngshān", "english": "mountain climbing", "russian": "альпинизм"},
  {"chinese": "滑冰", "pinyin": "huábīng", "english": "ice skating", "russian": "катание на коньках"},
  {"chinese": "滑雪", "pinyin": "huáxuě", "english": "skiing", "russian": "катание на лыжах"},
  {"chinese": "公园", "pinyin": "gōngyuán", "english": "park", "russian": "парк"},
  {"chinese": "博物馆", "pinyin": "báowùguǎn", "english": "museum", "russian": "музей"},
  {"chinese": "电影院", "pinyin": "diànyǐngyuàn", "english": "cinema", "russian": "кинотеатр"},
  {"chinese": "剧院", "pinyin": "jùyuàn", "english": "theatre", "russian": "театр"},
  {"chinese": "餐厅", "pinyin": "cāntīng", "english": "restaurant", "russian": "ресторан"},
  {"chinese": "咖啡厅", "pinyin": "kāfēitīng", "english": "cafe", "russian": "кафе"},
  {"chinese": "酒吧", "pinyin": "jiǔbā", "english": "bar", "russian": "бар"},
  {"chinese": "超市", "pinyin": "chāoshì", "english": "supermarket", "russian": "супермаркет"},
  {"chinese": "商店", "pinyin": "shāngdiàn", "english": "shop", "russian": "магазин"},
  {"chinese": "市场", "pinyin": "shìchǎng", "english": "market", "russian": "рынок"},
  {"chinese": "邮局", "pinyin": "yóujú", "english": "post office", "russian": "почта"},
  {"chinese": "银行", "pinyin": "yínhang", "english": "bank", "russian": "банк"},
  {"chinese": "车站", "pinyin": "chēzhàn", "english": "station", "russian": "станция"},
  {"chinese": "飞机场", "pinyin": "fēijīchǎng", "english": "airport", "russian": "аэропорт"},
  {"chinese": "出租车", "pinyin": "chūzūchē", "english": "taxi", "russian": "такси"},
  {"chinese": "公交车", "pinyin": "gōngjiāochē", "english": "bus", "russian": "автобус"},
  {"chinese": "地铁", "pinyin": "dìtiě", "english": "metro", "russian": "метро"},
  {"chinese": "火车", "pinyin": "huǒchē", "english": "train", "russian": "поезд"},
  {"chinese": "自行车", "pinyin": "zìxíngchē", "english": "bicycle", "russian": "велосипед"},
  {"chinese": "汽车", "pinyin": "qìchē", "english": "car", "russian": "автомобиль"},
  {"chinese": "船", "pinyin": "chuán", "english": "ship", "russian": "корабль"},
  {"chinese": "飞机", "pinyin": "fēijī", "english": "airplane", "russian": "самолёт"},
  {"chinese": "行李", "pinyin": "xíngli", "english": "luggage", "russian": "багаж"},
  {"chinese": "票", "pinyin": "piào", "english": "ticket", "russian": "билет"},
  {"chinese": "月", "pinyin": "yuè", "english": "month", "russian": "месяц"},
  {"chinese": "春天", "pinyin": "chūntiān", "english": "spring", "russian": "весна"},
  {"chinese": "夏天", "pinyin": "xiàtiān", "english": "summer", "russian": "лето"},
  {"chinese": "秋天", "pinyin": "qiūtiān", "english": "autumn", "russian": "осень"},
  {"chinese": "冬天", "pinyin": "dōngtiān", "english": "winter", "russian": "зима"},
  {"chinese": "天气", "pinyin": "tiānqì", "english": "weather", "russian": "погода"},
  {"chinese": "晴天", "pinyin": "qīngtiān", "english": "sunny day", "russian": "солнечный день"},
  {"chinese": "下雨", "pinyin": "xiàyǔ", "english": "to rain", "russian": "идёт дождь"},
  {"chinese": "下雪", "pinyin": "xiàxuě", "english": "to snow", "russian": "идёт снег"},
  {"chinese": "风", "pinyin": "fēng", "english": "wind", "russian": "ветер"},
  {"chinese": "雾", "pinyin": "wù", "english": "fog", "russian": "туман"},
  {"chinese": "云", "pinyin": "yún", "english": "cloud", "russian": "облако"},
  {"chinese": "星星", "pinyin": "xīngxing", "english": "star", "russian": "звезда"},
  {"chinese": "太阳", "pinyin": "tàiyáng", "english": "sun", "russian": "солнце"},
  {"chinese": "月亮", "pinyin": "yuèliàng", "english": "moon", "russian": "луна"},
  {"chinese": "颜色", "pinyin": "yánsè", "english": "color", "russian": "цвет"},
  {"chinese": "红", "pinyin": "hóng", "english": "red", "russian": "красный"},
  {"chinese": "黄", "pinyin": "huáng", "english": "yellow", "russian": "жёлтый"},
  {"chinese": "蓝", "pinyin": "lán", "english": "blue", "russian": "синий"},
  {"chinese": "绿", "pinyin": "lǜ", "english": "green", "russian": "зелёный"},
  {"chinese": "黑", "pinyin": "hēi", "english": "black", "russian": "чёрный"},
  {"chinese": "白", "pinyin": "bái", "english": "white", "russian": "белый"},
  {"chinese": "粉红色", "pinyin": "fěnhóng sè", "english": "pink", "russian": "розовый"},
  {"chinese": "紫色", "pinyin": "zǐsè", "english": "purple", "russian": "фиолетовый"},
  {"chinese": "灰色", "pinyin": "huīsè", "english": "gray", "russian": "серый"},
  {"chinese": "棕色", "pinyin": "zōngsè", "english": "brown", "russian": "коричневый"},
  {"chinese": "橙色", "pinyin": "chéngsè", "english": "orange", "russian": "оранжевый"},
  {"chinese": "金色", "pinyin": "jīnsè", "english": "gold", "russian": "золотой"},
  {"chinese": "银色", "pinyin": "yínsè", "english": "silver", "russian": "серебристый"},
  {"chinese": "名字", "pinyin": "míngzi", "english": "name", "russian": "имя"},
  {"chinese": "年龄", "pinyin": "niánlìng", "english": "age", "russian": "возраст"},
  {"chinese": "出生", "pinyin": "chūshēng", "english": "birth", "russian": "рождение"},
  {"chinese": "死亡", "pinyin": "sǐwáng", "english": "death", "russian": "смерть"},
  {"chinese": "婚礼", "pinyin": "hūnlǐ", "english": "wedding", "russian": "свадьба"},
  {"chinese": "离婚", "pinyin": "líhūn", "english": "divorce", "russian": "развод"},
  {"chinese": "结婚", "pinyin": "jiéhūn", "english": "to marry", "russian": "жениться"},
  {"chinese": "日期", "pinyin": "rìqī", "english": "date", "russian": "дата"},
  {"chinese": "星期", "pinyin": "xīngqī", "english": "week", "russian": "неделя"},
  {"chinese": "星期一", "pinyin": "xīngqī yī", "english": "Monday", "russian": "понедельник"},
  {"chinese": "星期二", "pinyin": "xīngqī èr", "english": "Tuesday", "russian": "вторник"},
  {"chinese": "星期三", "pinyin": "xīngqī sān", "english": "Wednesday", "russian": "среда"},
  {"chinese": "星期四", "pinyin": "xīngqī sì", "english": "Thursday", "russian": "четверг"},
  {"chinese": "星期五", "pinyin": "xīngqī wǔ", "english": "Friday", "russian": "пятница"},
  {"chinese": "星期六", "pinyin": "xīngqī liù", "english": "Saturday", "russian": "суббота"},
  {"chinese": "星期日", "pinyin": "xīngqī rì", "english": "Sunday", "russian": "воскресенье"},
  {"chinese": "时间", "pinyin": "shíjiān", "english": "time", "russian": "время"},
  {"chinese": "小时", "pinyin": "xiǎoshí", "english": "hour", "russian": "час"},
  {"chinese": "分钟", "pinyin": "fēnzhōng", "english": "minute", "russian": "минута"},
  {"chinese": "秒", "pinyin": "miǎo", "english": "second", "russian": "секунда"},
  {"chinese": "早上", "pinyin": "zǎoshang", "english": "morning", "russian": "утро"},
  {"chinese": "上午", "pinyin": "shàngwǔ", "english": "morning", "russian": "утро"},
  {"chinese": "中午", "pinyin": "zhōngwǔ", "english": "noon", "russian": "полдень"},
  {"chinese": "下午", "pinyin": "xiàwǔ", "english": "afternoon", "russian": "день"},
  {"chinese": "晚上", "pinyin": "wǎnshang", "english": "evening", "russian": "вечер"},
  {"chinese": "夜晚", "pinyin": "yèwǎn", "english": "night", "russian": "ночь"},
  {"chinese": "午夜", "pinyin": "wǔyè", "english": "midnight", "russian": "полночь"},
  {"chinese": "现在", "pinyin": "xiànzài", "english": "now", "russian": "сейчас"},
  {"chinese": "以前", "pinyin": "yǐqián", "english": "before", "russian": "раньше"},
  {"chinese": "以后", "pinyin": "yǐhòu", "english": "after", "russian": "позже"},
  {"chinese": "今天", "pinyin": "jīntiān", "english": "today", "russian": "сегодня"},
  {"chinese": "昨天", "pinyin": "zuótiān", "english": "yesterday", "russian": "вчера"},
  {"chinese": "明天", "pinyin": "míngtiān", "english": "tomorrow", "russian": "завтра"},
  {"chinese": "今年", "pinyin": "jīnnián", "english": "this year", "russian": "в этом году"},
  {"chinese": "去年", "pinyin": "qùnián", "english": "last year", "russian": "в прошлом году"},
  {"chinese": "明年", "pinyin": "mínnián", "english": "next year", "russian": "в следующем году"},
  {"chinese": "现代", "pinyin": "xiàndài", "english": "modern", "russian": "современный"},
  {"chinese": "古代", "pinyin": "gǔdài", "english": "ancient", "russian": "древний"},
  {"chinese": "中国", "pinyin": "Zhōngguó", "english": "China", "russian": "Китай"},
  {"chinese": "日本", "pinyin": "Rìběn", "english": "Japan", "russian": "Япония"},
  {"chinese": "美国", "pinyin": "Měiguó", "english": "United States", "russian": "Соединённые Штаты"},
  {"chinese": "英国", "pinyin": "Yīngguó", "english": "United Kingdom", "russian": "Великобритания"},
  {"chinese": "法国", "pinyin": "Fǎguó", "english": "France", "russian": "Франция"},
  {"chinese": "德国", "pinyin": "Déguó", "english": "Germany", "russian": "Германия"},
  {"chinese": "俄罗斯", "pinyin": "Éluósī", "english": "Russia", "russian": "Россия"},
  {"chinese": "印度", "pinyin": "Yìndù", "english": "India", "russian": "Индия"},
  {"chinese": "泰国", "pinyin": "Tàiguó", "english": "Thailand", "russian": "Таиланд"},
  {"chinese": "越南", "pinyin": "Yuènán", "english": "Vietnam", "russian": "Вьетнам"},
  {"chinese": "韩国", "pinyin": "Hánguó", "english": "South Korea", "russian": "Южная Корея"},
  {"chinese": "新加坡", "pinyin": "Xīnjiāpō", "english": "Singapore", "russian": "Сингапур"},
  {"chinese": "马来西亚", "pinyin": "Mǎláixīyà", "english": "Malaysia", "russian": "Малайзия"},
  {"chinese": "印度尼西亚", "pinyin": "Yìndùníxīyà", "english": "Indonesia", "russian": "Индонезия"},
  {"chinese": "菲律宾", "pinyin": "Fēilǜbīn", "english": "Philippines", "russian": "Филиппины"},
  {"chinese": "澳大利亚", "pinyin": "Àodàlìyà", "english": "Australia", "russian": "Австралия"},
  {"chinese": "新西兰", "pinyin": "Xīnxīlán", "english": "New Zealand", "russian": "Новая Зеландия"},
  {"chinese": "加拿大", "pinyin": "Jiānádà", "english": "Canada", "russian": "Канада"},
  {"chinese": "墨西哥", "pinyin": "Mòxīgē", "english": "Mexico", "russian": "Мексика"},
  {"chinese": "巴西", "pinyin": "Bāxī", "english": "Brazil", "russian": "Бразилия"},
  {"chinese": "阿根廷", "pinyin": "Āgēntíng", "english": "Argentina", "russian": "Аргентина"},
  {"chinese": "南非", "pinyin": "Nánfēi", "english": "South Africa", "russian": "Южная Африка"},
  {"chinese": "埃及", "pinyin": "Āijí", "english": "Egypt", "russian": "Египет"},
  {"chinese": "肯尼亚", "pinyin": "Kěnníyà", "english": "Kenya", "russian": "Кения"}
];