window.radicals = [
    // Stroke 1
    { char: '一', pinyin: 'yī',    russian: 'один',                   strokes: 1 },
    { char: '丨', pinyin: 'gǔn',   russian: 'вертикальная черта',     strokes: 1 },
    { char: '丶', pinyin: 'zhǔ',   russian: 'точка',                  strokes: 1 },
    { char: '丿', pinyin: 'piě',   russian: 'откидная черта влево',   strokes: 1 },
    { char: '乙', pinyin: 'yǐ',    russian: 'второй небесный ствол',  strokes: 1 },
    { char: '亅', pinyin: 'jué',   russian: 'крюк',                   strokes: 1 },
    // Stroke 2
    { char: '二', pinyin: 'èr',    russian: 'два',                    strokes: 2 },
    { char: '亠', pinyin: 'tóu',   russian: 'крышка',                 strokes: 2 },
    { char: '人', pinyin: 'rén',   russian: 'человек',                strokes: 2 },
    { char: '儿', pinyin: 'ér',    russian: 'ноги человека',          strokes: 2 },
    { char: '入', pinyin: 'rù',    russian: 'входить',                strokes: 2 },
    { char: '八', pinyin: 'bā',    russian: 'восемь',                 strokes: 2 },
    { char: '冂', pinyin: 'jiōng', russian: 'внешняя рамка',          strokes: 2 },
    { char: '冖', pinyin: 'mì',    russian: 'покров',                 strokes: 2 },
    { char: '冫', pinyin: 'bīng',  russian: 'лёд',                    strokes: 2 },
    { char: '几', pinyin: 'jī',    russian: 'столик',                 strokes: 2 },
    { char: '凵', pinyin: 'kǎn',   russian: 'вместилище',             strokes: 2 },
    { char: '刀', pinyin: 'dāo',   russian: 'нож',                    strokes: 2 },
    { char: '力', pinyin: 'lì',    russian: 'сила',                   strokes: 2 },
    { char: '勺', pinyin: 'sháo',  russian: 'ложка',                  strokes: 2 },
    { char: '匕', pinyin: 'bǐ',    russian: 'нож-ложка',              strokes: 2 },
    { char: '匚', pinyin: 'fāng',  russian: 'ящик',                   strokes: 2 },
    { char: '匸', pinyin: 'xì',    russian: 'скрыть',                 strokes: 2 },
    { char: '十', pinyin: 'shí',   russian: 'десять',                 strokes: 2 },
    { char: '卜', pinyin: 'bǔ',    russian: 'гадать',                 strokes: 2 },
    { char: '卩', pinyin: 'jié',   russian: 'печать',                 strokes: 2 },
    { char: '厂', pinyin: 'hǎn',   russian: 'обрыв / скала',          strokes: 2 },
    { char: '厶', pinyin: 'sī',    russian: 'личный',                 strokes: 2 },
    { char: '又', pinyin: 'yòu',   russian: 'снова / рука',           strokes: 2 },
    // Stroke 3
    { char: '口', pinyin: 'kǒu',   russian: 'рот',                    strokes: 3 },
    { char: '囗', pinyin: 'wéi',   russian: 'ограждение',             strokes: 3 },
    { char: '土', pinyin: 'tǔ',    russian: 'земля',                  strokes: 3 },
    { char: '士', pinyin: 'shì',   russian: 'воин / учёный',          strokes: 3 },
    { char: '夂', pinyin: 'zhǐ',   russian: 'идти медленно',          strokes: 3 },
    { char: '夊', pinyin: 'suī',   russian: 'медленно шагать',        strokes: 3 },
    { char: '夕', pinyin: 'xī',    russian: 'вечер',                  strokes: 3 },
    { char: '大', pinyin: 'dà',    russian: 'большой',                strokes: 3 },
    { char: '女', pinyin: 'nǚ',    russian: 'женщина',                strokes: 3 },
    { char: '子', pinyin: 'zǐ',    russian: 'ребёнок',                strokes: 3 },
    { char: '宀', pinyin: 'mián',  russian: 'крыша',                  strokes: 3 },
    { char: '寸', pinyin: 'cùn',   russian: 'мера длины цунь',        strokes: 3 },
    { char: '小', pinyin: 'xiǎo',  russian: 'маленький',              strokes: 3 },
    { char: '尢', pinyin: 'wāng',  russian: 'хромой',                 strokes: 3 },
    { char: '尸', pinyin: 'shī',   russian: 'тело / труп',            strokes: 3 },
    { char: '屮', pinyin: 'chè',   russian: 'росток',                 strokes: 3 },
    { char: '山', pinyin: 'shān',  russian: 'гора',                   strokes: 3 },
    { char: '巛', pinyin: 'chuān', russian: 'река',                   strokes: 3 },
    { char: '工', pinyin: 'gōng',  russian: 'работа',                 strokes: 3 },
    { char: '己', pinyin: 'jǐ',    russian: 'себя',                   strokes: 3 },
    { char: '巾', pinyin: 'jīn',   russian: 'платок',                 strokes: 3 },
    { char: '干', pinyin: 'gān',   russian: 'сухой / ствол',          strokes: 3 },
    { char: '幺', pinyin: 'yāo',   russian: 'крошечный',              strokes: 3 },
    { char: '广', pinyin: 'guǎng', russian: 'навес',                  strokes: 3 },
    { char: '廴', pinyin: 'yǐn',   russian: 'долгий шаг',             strokes: 3 },
    { char: '廾', pinyin: 'gǒng',  russian: 'обе руки',               strokes: 3 },
    { char: '弋', pinyin: 'yì',    russian: 'кол с нитью',            strokes: 3 },
    { char: '弓', pinyin: 'gōng',  russian: 'лук (оружие)',           strokes: 3 },
    { char: '彐', pinyin: 'jì',    russian: 'голова свиньи',          strokes: 3 },
    { char: '彡', pinyin: 'shān',  russian: 'узор / волосы',          strokes: 3 },
    { char: '彳', pinyin: 'chì',   russian: 'маленький шаг',          strokes: 3 },
    // Stroke 4
    { char: '心', pinyin: 'xīn',   russian: 'сердце',                 strokes: 4 },
    { char: '戈', pinyin: 'gē',    russian: 'алебарда',               strokes: 4 },
    { char: '戶', pinyin: 'hù',    russian: 'дверь / домохозяйство',  strokes: 4 },
    { char: '手', pinyin: 'shǒu',  russian: 'рука',                   strokes: 4 },
    { char: '支', pinyin: 'zhī',   russian: 'ветвь',                  strokes: 4 },
    { char: '攴', pinyin: 'pū',    russian: 'ударять',                strokes: 4 },
    { char: '文', pinyin: 'wén',   russian: 'письмо / культура',      strokes: 4 },
    { char: '斗', pinyin: 'dǒu',   russian: 'ковш / бороться',        strokes: 4 },
    { char: '斤', pinyin: 'jīn',   russian: 'топор / цзинь (мера)',   strokes: 4 },
    { char: '方', pinyin: 'fāng',  russian: 'квадрат / сторона',      strokes: 4 },
    { char: '无', pinyin: 'wú',    russian: 'нет / без',              strokes: 4 },
    { char: '日', pinyin: 'rì',    russian: 'солнце / день',          strokes: 4 },
    { char: '曰', pinyin: 'yuē',   russian: 'говорить',               strokes: 4 },
    { char: '月', pinyin: 'yuè',   russian: 'луна / месяц',           strokes: 4 },
    { char: '木', pinyin: 'mù',    russian: 'дерево',                 strokes: 4 },
    { char: '欠', pinyin: 'qiàn',  russian: 'зевать / задолжать',     strokes: 4 },
    { char: '止', pinyin: 'zhǐ',   russian: 'остановиться',           strokes: 4 },
    { char: '歹', pinyin: 'dǎi',   russian: 'плохой / кость',         strokes: 4 },
    { char: '殳', pinyin: 'shū',   russian: 'копьё (оружие)',         strokes: 4 },
    { char: '毋', pinyin: 'wú',    russian: 'не (запрет)',            strokes: 4 },
    { char: '比', pinyin: 'bǐ',    russian: 'сравнивать',             strokes: 4 },
    { char: '毛', pinyin: 'máo',   russian: 'волос / шерсть',         strokes: 4 },
    { char: '氏', pinyin: 'shì',   russian: 'клан / фамилия',         strokes: 4 },
    { char: '气', pinyin: 'qì',    russian: 'воздух / дыхание / ци',  strokes: 4 },
    { char: '水', pinyin: 'shuǐ',  russian: 'вода',                   strokes: 4 },
    { char: '火', pinyin: 'huǒ',   russian: 'огонь',                  strokes: 4 },
    { char: '爪', pinyin: 'zhǎo',  russian: 'коготь',                 strokes: 4 },
    { char: '父', pinyin: 'fù',    russian: 'отец',                   strokes: 4 },
    { char: '爻', pinyin: 'yáo',   russian: 'черта гексаграммы',      strokes: 4 },
    { char: '爿', pinyin: 'qiáng', russian: 'кусок дерева',           strokes: 4 },
    { char: '片', pinyin: 'piàn',  russian: 'пластина / кусок',       strokes: 4 },
    { char: '牙', pinyin: 'yá',    russian: 'зуб / клык',             strokes: 4 },
    { char: '牛', pinyin: 'niú',   russian: 'корова / бык',           strokes: 4 },
    { char: '犬', pinyin: 'quǎn',  russian: 'собака',                 strokes: 4 },
    // Stroke 5
    { char: '玄', pinyin: 'xuán',  russian: 'тёмный / таинственный',  strokes: 5 },
    { char: '玉', pinyin: 'yù',    russian: 'нефрит',                 strokes: 5 },
    { char: '瓜', pinyin: 'guā',   russian: 'дыня',                   strokes: 5 },
    { char: '瓦', pinyin: 'wǎ',    russian: 'черепица',               strokes: 5 },
    { char: '甘', pinyin: 'gān',   russian: 'сладкий',                strokes: 5 },
    { char: '生', pinyin: 'shēng', russian: 'рождаться / жить',       strokes: 5 },
    { char: '用', pinyin: 'yòng',  russian: 'использовать',           strokes: 5 },
    { char: '田', pinyin: 'tián',  russian: 'поле',                   strokes: 5 },
    { char: '疋', pinyin: 'pǐ',    russian: 'рулон ткани',            strokes: 5 },
    { char: '疒', pinyin: 'nè',    russian: 'болезнь',                strokes: 5 },
    { char: '癶', pinyin: 'bō',    russian: 'шагать / расступаться',  strokes: 5 },
    { char: '白', pinyin: 'bái',   russian: 'белый',                  strokes: 5 },
    { char: '皮', pinyin: 'pí',    russian: 'кожа',                   strokes: 5 },
    { char: '皿', pinyin: 'mǐn',   russian: 'сосуд / миска',          strokes: 5 },
    { char: '目', pinyin: 'mù',    russian: 'глаз',                   strokes: 5 },
    { char: '矛', pinyin: 'máo',   russian: 'копьё',                  strokes: 5 },
    { char: '矢', pinyin: 'shǐ',   russian: 'стрела',                 strokes: 5 },
    { char: '石', pinyin: 'shí',   russian: 'камень',                 strokes: 5 },
    { char: '示', pinyin: 'shì',   russian: 'показывать / духи',      strokes: 5 },
    { char: '禸', pinyin: 'róu',   russian: 'след животного',         strokes: 5 },
    { char: '禾', pinyin: 'hé',    russian: 'зерно / колос',          strokes: 5 },
    { char: '穴', pinyin: 'xué',   russian: 'нора / пещера',          strokes: 5 },
    { char: '立', pinyin: 'lì',    russian: 'стоять',                 strokes: 5 },
    // Stroke 6
    { char: '竹', pinyin: 'zhú',   russian: 'бамбук',                 strokes: 6 },
    { char: '米', pinyin: 'mǐ',    russian: 'рис',                    strokes: 6 },
    { char: '糸', pinyin: 'sī',    russian: 'нить / шёлк',            strokes: 6 },
    { char: '缶', pinyin: 'fǒu',   russian: 'кувшин',                 strokes: 6 },
    { char: '网', pinyin: 'wǎng',  russian: 'сеть',                   strokes: 6 },
    { char: '羊', pinyin: 'yáng',  russian: 'овца / баран',           strokes: 6 },
    { char: '羽', pinyin: 'yǔ',    russian: 'перо',                   strokes: 6 },
    { char: '老', pinyin: 'lǎo',   russian: 'старый',                 strokes: 6 },
    { char: '而', pinyin: 'ér',    russian: 'и / но / бородка',       strokes: 6 },
    { char: '耒', pinyin: 'lěi',   russian: 'плуг',                   strokes: 6 },
    { char: '耳', pinyin: 'ěr',    russian: 'ухо',                    strokes: 6 },
    { char: '聿', pinyin: 'yù',    russian: 'кисть для письма',       strokes: 6 },
    { char: '肉', pinyin: 'ròu',   russian: 'мясо',                   strokes: 6 },
    { char: '臣', pinyin: 'chén',  russian: 'чиновник',               strokes: 6 },
    { char: '自', pinyin: 'zì',    russian: 'сам / от',               strokes: 6 },
    { char: '至', pinyin: 'zhì',   russian: 'достигать',              strokes: 6 },
    { char: '臼', pinyin: 'jiù',   russian: 'ступа',                  strokes: 6 },
    { char: '舌', pinyin: 'shé',   russian: 'язык (орган)',           strokes: 6 },
    { char: '舛', pinyin: 'chuǎn', russian: 'идти неровно',           strokes: 6 },
    { char: '舟', pinyin: 'zhōu',  russian: 'лодка',                  strokes: 6 },
    { char: '艮', pinyin: 'gèn',   russian: 'твёрдый / предел',       strokes: 6 },
    { char: '色', pinyin: 'sè',    russian: 'цвет',                   strokes: 6 },
    { char: '艸', pinyin: 'cǎo',   russian: 'трава',                  strokes: 6 },
    { char: '虍', pinyin: 'hū',    russian: 'тигр (часть)',           strokes: 6 },
    { char: '虫', pinyin: 'chóng', russian: 'насекомое',              strokes: 6 },
    { char: '血', pinyin: 'xuè',   russian: 'кровь',                  strokes: 6 },
    { char: '行', pinyin: 'xíng',  russian: 'идти / ряд',             strokes: 6 },
    { char: '衣', pinyin: 'yī',    russian: 'одежда',                 strokes: 6 },
    { char: '襾', pinyin: 'yà',    russian: 'крышка',                 strokes: 6 },
    // Stroke 7
    { char: '見', pinyin: 'jiàn',  russian: 'видеть',                 strokes: 7 },
    { char: '角', pinyin: 'jiǎo',  russian: 'угол / рог',             strokes: 7 },
    { char: '言', pinyin: 'yán',   russian: 'говорить / слово',       strokes: 7 },
    { char: '谷', pinyin: 'gǔ',    russian: 'долина',                 strokes: 7 },
    { char: '豆', pinyin: 'dòu',   russian: 'боб',                    strokes: 7 },
    { char: '豕', pinyin: 'shǐ',   russian: 'свинья',                 strokes: 7 },
    { char: '豸', pinyin: 'zhì',   russian: 'хищный зверь',           strokes: 7 },
    { char: '貝', pinyin: 'bèi',   russian: 'ракушка / богатство',    strokes: 7 },
    { char: '赤', pinyin: 'chì',   russian: 'красный',                strokes: 7 },
    { char: '走', pinyin: 'zǒu',   russian: 'идти / бежать',          strokes: 7 },
    { char: '足', pinyin: 'zú',    russian: 'нога / достаточно',      strokes: 7 },
    { char: '身', pinyin: 'shēn',  russian: 'тело',                   strokes: 7 },
    { char: '車', pinyin: 'chē',   russian: 'повозка',                strokes: 7 },
    { char: '辛', pinyin: 'xīn',   russian: 'острый / горький',       strokes: 7 },
    { char: '辰', pinyin: 'chén',  russian: 'время / дракон (ветвь)', strokes: 7 },
    { char: '辵', pinyin: 'chuò',  russian: 'идти / движение',        strokes: 7 },
    { char: '邑', pinyin: 'yì',    russian: 'город / поселение',      strokes: 7 },
    { char: '酉', pinyin: 'yǒu',   russian: 'петух / ферментация',    strokes: 7 },
    { char: '釆', pinyin: 'biàn',  russian: 'различать',              strokes: 7 },
    { char: '里', pinyin: 'lǐ',    russian: 'деревня / ли (мера)',    strokes: 7 },
    // Stroke 8
    { char: '金', pinyin: 'jīn',   russian: 'золото / металл',        strokes: 8 },
    { char: '長', pinyin: 'zhǎng', russian: 'длинный / старший',      strokes: 8 },
    { char: '門', pinyin: 'mén',   russian: 'дверь / ворота',         strokes: 8 },
    { char: '阜', pinyin: 'fù',    russian: 'холм / земляной вал',    strokes: 8 },
    { char: '隶', pinyin: 'lì',    russian: 'достигать / подчинённый',strokes: 8 },
    { char: '隹', pinyin: 'zhuī',  russian: 'короткохвостая птица',   strokes: 8 },
    { char: '雨', pinyin: 'yǔ',    russian: 'дождь',                  strokes: 8 },
    { char: '靑', pinyin: 'qīng',  russian: 'синий / зелёный / юный', strokes: 8 },
    { char: '非', pinyin: 'fēi',   russian: 'не / неправильный',      strokes: 8 },
    // Stroke 9
    { char: '面', pinyin: 'miàn',  russian: 'лицо / поверхность',     strokes: 9 },
    { char: '革', pinyin: 'gé',    russian: 'выделанная кожа',        strokes: 9 },
    { char: '韋', pinyin: 'wéi',   russian: 'мягкая кожа',            strokes: 9 },
    { char: '韭', pinyin: 'jiǔ',   russian: 'лук-порей',              strokes: 9 },
    { char: '音', pinyin: 'yīn',   russian: 'звук / музыка',          strokes: 9 },
    { char: '頁', pinyin: 'yè',    russian: 'страница / голова',      strokes: 9 },
    { char: '風', pinyin: 'fēng',  russian: 'ветер',                  strokes: 9 },
    { char: '飛', pinyin: 'fēi',   russian: 'летать',                 strokes: 9 },
    { char: '食', pinyin: 'shí',   russian: 'есть / пища',            strokes: 9 },
    { char: '首', pinyin: 'shǒu',  russian: 'голова / первый',        strokes: 9 },
    { char: '香', pinyin: 'xiāng', russian: 'аромат / благовоние',    strokes: 9 },
    // Stroke 10
    { char: '馬', pinyin: 'mǎ',    russian: 'лошадь',                 strokes: 10 },
    { char: '骨', pinyin: 'gǔ',    russian: 'кость',                  strokes: 10 },
    { char: '高', pinyin: 'gāo',   russian: 'высокий',                strokes: 10 },
    { char: '髟', pinyin: 'biāo',  russian: 'длинные волосы',         strokes: 10 },
    { char: '鬥', pinyin: 'dòu',   russian: 'драться / бороться',     strokes: 10 },
    { char: '鬯', pinyin: 'chàng', russian: 'ритуальный напиток',     strokes: 10 },
    { char: '鬲', pinyin: 'lì',    russian: 'котёл-треножник',        strokes: 10 },
    { char: '鬼', pinyin: 'guǐ',   russian: 'призрак / дух',          strokes: 10 },
    // Stroke 11
    { char: '魚', pinyin: 'yú',    russian: 'рыба',                   strokes: 11 },
    { char: '鳥', pinyin: 'niǎo',  russian: 'птица',                  strokes: 11 },
    { char: '鹵', pinyin: 'lǔ',    russian: 'соль / рассол',          strokes: 11 },
    { char: '鹿', pinyin: 'lù',    russian: 'олень',                  strokes: 11 },
    { char: '麥', pinyin: 'mài',   russian: 'пшеница',                strokes: 11 },
    { char: '麻', pinyin: 'má',    russian: 'конопля / онемение',     strokes: 11 },
    // Stroke 12
    { char: '黃', pinyin: 'huáng', russian: 'жёлтый',                 strokes: 12 },
    { char: '黍', pinyin: 'shǔ',   russian: 'просо',                  strokes: 12 },
    { char: '黑', pinyin: 'hēi',   russian: 'чёрный',                 strokes: 12 },
    { char: '黹', pinyin: 'zhǐ',   russian: 'вышивка',                strokes: 12 },
    // Stroke 13
    { char: '黽', pinyin: 'miǎn',  russian: 'лягушка',                strokes: 13 },
    { char: '鼎', pinyin: 'dǐng',  russian: 'треножный котёл',        strokes: 13 },
    { char: '鼓', pinyin: 'gǔ',    russian: 'барабан',                strokes: 13 },
    { char: '鼠', pinyin: 'shǔ',   russian: 'мышь / крыса',           strokes: 13 },
    // Stroke 14
    { char: '鼻', pinyin: 'bí',    russian: 'нос',                    strokes: 14 },
    { char: '齊', pinyin: 'qí',    russian: 'ровный / одновременно',  strokes: 14 },
    // Stroke 15
    { char: '齒', pinyin: 'chǐ',   russian: 'зуб',                    strokes: 15 },
    { char: '龍', pinyin: 'lóng',  russian: 'дракон',                 strokes: 15 },
    // Stroke 16
    { char: '龜', pinyin: 'guī',   russian: 'черепаха',               strokes: 16 },
    // Stroke 17
    { char: '龠', pinyin: 'yuè',   russian: 'флейта',                 strokes: 17 },
];
